# Generated by Django 2.0.2 on 2018-03-26 17:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=200)),
                ('input_text', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
