# Generated by Django 2.0.2 on 2018-03-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='input_name',
            field=models.CharField(max_length=50),
        ),
    ]
