# Generated by Django 2.0.2 on 2018-03-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20180329_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputs',
            name='input_name',
        ),
    ]
